export const menuItemsHome = [
    {
        key: "1",
        icon: "/img/c.png",
        label: "Nguyễn Thế Đạt",
        isFirstImage: true,
        link: "/",
    },
    {
        key: "2",
        icon: "/img/img-header/user/ep_icon_friend.svg",
        label: "Bạn bè",
        link: "/",
    },
    {
        key: "3",
        icon: "/img/img-header/user/ep_icon_group.svg",
        label: "Nhóm",
        link: "/",
    },
    {
        key: "4",
        icon: "/img/img-header/user/ep_icon_save.svg",
        label: "Đã lưu",
        link: "/",
    },
    {
        key: "5",
        icon: "/img/img-header/user/ep_info_event.svg",
        label: "Sự kiện",
        link: "/",
    },
    {
        key: "6",
        icon: "/img/img-header/user/ep_info_mess.svg",
        label: "Tin nhắn",
        link: "/",
    },
    {
        key: "7",
        icon: "/img/img-header/user/ep_info_kn.svg",
        label: "Sự kiện",
        link: "/",
    },
];

export const menuItemsHomeContact = [
    {
        key: "1",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "2",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    },
    {
        key: "3",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "4",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    },
    {
        key: "5",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "6",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    },
    {
        key: "7",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "8",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    },
    {
        key: "9",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "10",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    }, {
        key: "1111",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: true,
    },
    {
        key: "12",
        link: "/",
        icon: "/img/c.png",
        name: "Nguyễn Thế Đạt",
        status: false,
    },
];